object Main {
  def main(arg:Array[String]) = {
    val in = readLine.split(" ")
    val deg = in(0).toInt
    val dis = in(1).toInt /  60.0
    if(dis < 0.25) print("C")
    else if(deg < 112.5 || deg >= 3487.5) print("N")
    else if(deg < 337.5)                  print("NNE")
    else if(deg < 562.5)                  print("NE")
    else if(deg < 787.5)                  print("ENE")
    else if(deg < 1012.5)                 print("E")
    else if(deg < 1237.5)                 print("ESE")
    else if(deg < 1462.5)                 print("SE")
    else if(deg < 1687.5)                 print("SSE")
    else if(deg < 1912.5)                 print("S")
    else if(deg < 2137.5)                 print("SSW")
    else if(deg < 2362.5)                 print("SW")
    else if(deg < 2587.5)                 print("WSW")
    else if(deg < 2812.5)                 print("W")
    else if(deg < 3037.5)                 print("WNW")
    else if(deg < 3262.5)                 print("NW")
    else if(deg < 3487.5)                 print("NNW")
    
    print(" ")
    if(dis < 0.25)       println(0)
    else if(dis < 1.55)  println(1)
    else if(dis < 3.35)  println(2)
    else if(dis < 5.45)  println(3)
    else if(dis < 7.95)  println(4)
    else if(dis < 10.75) println(5)
    else if(dis < 13.85) println(6)
    else if(dis < 17.15) println(7)
    else if(dis < 20.75) println(8)
    else if(dis < 24.45) println(9)
    else if(dis < 28.45) println(10)
    else if(dis < 32.65) println(11)
    else                 println(12)
  }
}
 // Main.main(null)
